[package]
name = "nu_plugin_plist"
description = "Plist parsing for nushell"
version = "0.91.0"
edition = "2021"
license = "MIT"


[dependencies]
plist = "1.6"
nu-plugin = "0.91"
nu-protocol = "0.91"
chrono = "0.4"
