[package]
name = "nu_plugin_plist"
description = "Plist parsing for nushell"
version = "0.89.1"
edition = "2021"
license = "MIT"


[dependencies]
plist = "1.6"
nu-plugin = "0.89"
nu-protocol = "0.89"
chrono = "0.4"
